<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mixline.Soundboard</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Mixline.Core.csproj" />
    <ProjectReference Include="..\Logging\Mixline.Logging.csproj" />
  </ItemGroup>
</Project>
